name: Push Docker Image to GitHub Packages

on:
  push:
    branches: [ main ]  # 当推送到 main 分支时触发

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: 拉取仓库代码
        uses: actions/checkout@v4

      - name: 加载 Docker 环境
        uses: docker/setup-buildx-action@v3

      - name: 登录 GitHub Packages
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # 检查tar文件是否存在
      - name: 检查my-image.tar是否存在
        id: check_tar
        run: |
          if [ -f "my-image.tar" ]; then
            echo "exists=true" >> $GITHUB_OUTPUT
          else
            echo "exists=false" >> $GITHUB_OUTPUT
          fi

      # 推送本地镜像（如果tar文件存在）
      - name: 从tar文件加载并推送镜像
        if: steps.check_tar.outputs.exists == 'true'
        run: |
          docker load -i my-image.tar
          # 注意：需要将"本地镜像名称:标签"替换为实际的镜像名称和标签
          docker tag 本地镜像名称:标签 ghcr.io/${{ github.repository_owner }}/my-image:latest
          docker push ghcr.io/${{ github.repository_owner }}/my-image:latest

      # 检查Dockerfile是否存在
      - name: 检查Dockerfile是否存在
        id: check_dockerfile
        run: |
          if [ -f "Dockerfile" ]; then
            echo "exists=true" >> $GITHUB_OUTPUT
          else
            echo "exists=false" >> $GITHUB_OUTPUT
          fi

      # 从Dockerfile构建并推送（如果Dockerfile存在）
      - name: 从Dockerfile构建并推送镜像
        if: steps.check_dockerfile.outputs.exists == 'true'
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/my-image:latest
